apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-api
spec:
  template:
    spec:
      containers:
      - name: checkout-api
        env:
        - name: CHECKOUT_MODE
          value: invalid-demo-mode
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 800m
            memory: 128Mi
